export enum AppPagePaths {
    // default
    ACCUEIL = '/',

    // main
    DEFINITION = '/definition',
    EQUIPE = '/equipe',
    AGENDA = '/agenda',
    STAGES = '/stages',
    ACCOMPAGNEMENT_INDIVIDUEL = '/stages/accompagnement-individuel-en-olfactocoaching',
    ANIMER_DES_GROUPES_AVEC_DES_ODEURS = '/stages/animer-des-groupes-avec-des-odeurs',
    VOYAGE_OLFACTIF_DU_HEROS = '/stages/le-voyage-olfactif-du-heros',
    ZOOM_LES_BASES_OLFACTOTHERAPIE = '/stages/zoom-les-bases-olfactotherapie',
    PREMIER_DEGRE_OLFACTOTHERAPIE = 'https://www.olfactotherapie.com/formation-d-olfactoth%C3%A9rapie/1er-degr%C3%A9-d-olfactoth%C3%A9rapie/',
    TEMOIGNAGES = '/temoignages',
    MATERIEL = '/materiel',
    MATERIEL_LE_COFFRET_DE_BASE_AVEC_LES_8_SYNERGIES = '/materiel/coffret-de-base',
    MATERIEL_UN_LOT_DE_TOUCHES_A_SENTIR = '/materiel/touches-a-sentir',
    MATERIEL_UN_SUPPORT_POUR_LES_TOUCHES_A_SENTIR = '/materiel/un-support-pour-les-touches-a-sentir',
    MATERIEL_LE_JEU_DE_CARTES_LES_ODEURS_QUESTIONNENT = '/materiel/le-jeu-de-cartes-les-odeurs-questionnent',
    MATERIEL_LES_16_ODEURS_DE_BASE_EN_RECHARGE = '/materiel/les-16-odeurs-de-base-en-recharge',
    ANNUAIRE = '/annuaire',
    RESSOURCES = '/ressources',

    // misc.
    MENTION_LEGALES = '/mentions',
    CONDITIONS = '/conditions',
    CONFIDENTIALITE = '/confidentialite',
    COOKIES = '/cookies',
    PLAN = '/plan',

    // other
    NOT_FOUND = '/not-found',
}

export enum AppThemes {
    LIGHT = 'light',
    DARK = 'dark',
}

export enum AppAuthors {
    ELISABETH_MOLINA = 'Elisabeth Molina',
    GILLES_FOURNIL = 'Gilles Fournil',
}

export enum AppPhotoIds {
    ACCOMPAGNEMENT_INDIVIDUEL = 'ACCOMPAGNEMENT_INDIVIDUEL',
    ANIMER_GROUPE_AVEC_ODEURS = 'ANIMER_GROUPE_AVEC_ODEURS',
    NEZ_LAVANDE = 'NEZ_LAVANDE',
    OC_MATERIEL_16_HE = 'OC_MATERIEL_16_HE',
    OC_MATERIEL_8_SYNERGIES = 'OC_MATERIEL_8_SYNERGIES',
    OC_MATERIEL_COFFRET_24 = 'OC_MATERIEL_COFFRET_24',
    OC_MATERIEL_JEU_ODEURS_QUESTIONNENT_1 = 'OC_MATERIEL_JEU_ODEURS_QUESTIONNENT_1',
    OC_MATERIEL_JEU_ODEURS_QUESTIONNENT_2 = 'OC_MATERIEL_JEU_ODEURS_QUESTIONNENT_2',
    OC_MATERIEL_JEU_ODEURS_QUESTIONNENT_3 = 'OC_MATERIEL_JEU_ODEURS_QUESTIONNENT_3',
    OC_MATERIEL_SUPPORT_TOUCHES_A_SENTIR_1 = 'OC_MATERIEL_SUPPORT_TOUCHES_A_SENTIR_1',
    OC_MATERIEL_SUPPORT_TOUCHES_A_SENTIR_2 = 'OC_MATERIEL_SUPPORT_TOUCHES_A_SENTIR_2',
    OC_MATERIEL_UN_LOT_DE_TOUCHES_A_SENTIR = 'OC_MATERIEL_UN_LOT_DE_TOUCHES_A_SENTIR',
    OLFACTOCOACHING_BANDEAU = 'OLFACTOCOACHING_BANDEAU',
    OLFACTOCOACHING_ELISABETH = 'OLFACTOCOACHING_ELISABETH',
    OLFACTOCOACHING_EQUIPE = 'OLFACTOCOACHING_EQUIPE',
    OLFACTOCOACHING_ETAPE_1 = 'OLFACTOCOACHING_ETAPE_1',
    OLFACTOCOACHING_ETAPE_2 = 'OLFACTOCOACHING_ETAPE_2',
    OLFACTOCOACHING_FLEUR = 'OLFACTOCOACHING_FLEUR',
    OLFACTOCOACHING_LES_ENJEUX = 'OLFACTOCOACHING_LES_ENJEUX',
    OLFACTOCOACHING_LES_SPECIFICITES = 'OLFACTOCOACHING_LES_SPECIFICITES',
    OLFACTOCOACHING_LOGO_INTRO = 'OLFACTOCOACHING_LOGO_INTRO',
    OLFACTOCOACHING_ODEURS_QUESTIONNENT = 'OLFACTOCOACHING_ODEURS_QUESTIONNENT',
    OLFACTOCOACHING_POST_FACEBOOK = 'OLFACTOCOACHING_POST_FACEBOOK',
    OLFACTOCOACHING_POUR_QUI = 'OLFACTOCOACHING_POUR_QUI',
    OLFACTOCOACHING_TEMOIGNAGE = 'OLFACTOCOACHING_TEMOIGNAGE',

    // unsplash
    VOYAGE_OLFACTIF_DU_HEROS = 'VOYAGE_OLFACTIF_DU_HEROS',
}

export enum AppFormationIds {
    STAGE_ACCOMPAGNEMENT_INDIVIDUEL = 'STAGE_ACCOMPAGNEMENT_INDIVIDUEL',
    STAGE_ZOOM_ANIMER_DES_GROUPES_AVEC_DES_ODEURS = 'STAGE_ZOOM_ANIMER_DES_GROUPES_AVEC_DES_ODEURS',
    STAGE_VOYAGE_OLFACTIF_DU_HEROS = 'STAGE_VOYAGE_OLFACTIF_DU_HEROS',
    ZOOM_LES_BASES_OLFACTOTHERAPIE = 'ZOOM_LES_BASES_OLFACTOTHERAPIE',
    ZOOM_PREMIER_DEGRE_OLFACTOTHERAPIE = 'ZOOM_PREMIER_DEGRE_OLFACTOTHERAPIE',
}
